### PR TITLE
fix: wrap -f with quotes

### LINKED ISSUE #63: Space in Directory structure breaks checkov scan
Hi Bridgecrew Team,

I'm testing out the chevkov-vscode plugin on a Windows 10 Endpoint with VS Code and using CFNGoat. Checkov throws an exception when using the plugin and its scanning a file that contains a space in the directory structure:
image

This issue can be fixed by encapsulating the cmdline argument in quotations e.g.
checkov -s --bc-api-key **** --repo-id bridgecrewio/cfngoat -f "c:\Users\XXX XXX\Documents\Bridgecrew\cfngoat\cfngoat.yaml" -o json 

Also - any future plans at this point to release an extension for Visual Studio?

### PR DESCRIPTION
**Pull request by paulmowat**
# In This PR

- When running on windows without docker installed and having checkov installed via PIP if you had a space in the file path name e.g. C:\temp\demo project\template.yaml then the scan would fail due to the space. Changes made are to wrap the -f arguments with quotes to ensure the full path is taken into account.

Fixes #63 

- [x] I've reviewed my own code

### CODE REVIEW

File: src/checkovRunner.ts [hunk 1]
```diff
@@ -51,8 +51,8 @@ const getDockerRunParams = (workspaceRoot: string | undefined, filePath: string,
     
     return configFilePath ?
         [...params, '-v', `"${path.dirname(configFilePath)}:${configMountDir}"`, image, 
-            '--config-file', `${configMountDir}/${path.basename(configFilePath)}`, '-f', filePathToScan] :
-        [...params, image, '-f', filePathToScan];
+            '--config-file', `${configMountDir}/${path.basename(configFilePath)}`, '-f', `"${filePathToScan}"`] :
+        [...params, image, '-f', `"filePathToScan"`];
```
Comment (rafaeelaudibert) [inline src/checkovRunner.ts:55]: Besides doing what I'm suggesting below, you could also change directly the `convertToUnixPath` function return
```suggestion
        [...params, image, '-f', `"${filePathToScan}"`];
```

**Review by rafaeelaudibert — CHANGES_REQUESTED** [review]

File: src/checkovRunner.ts (hunk 1 above)
Comment (paulmowat) [reply src/checkovRunner.ts]: I've made the change to convertToUnixPath function to wrap in there. if we do it there we don't need to do it within the getDockerRunParams function directly, otherwise they would be double quoted.

**Review by SteveVaknin — APPROVED** [review]
Looks good
@paulmowat Thanks!
